version: '3.8'

services:
  db5:
    image: postgres:latest
    container_name: borrowing_container
    environment:
      POSTGRES_USER: user5
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: db5
    ports:
      - "5436:5432"
    volumes:
      - db5-data:/var/lib/postgresql/data

volumes:
  db5-data: