apiVersion: v1
kind: ResourceQuota
metadata:
  name: borrowing-service-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
    configmaps: "10"
    secrets: "10"