apiVersion: v1
kind: Service
metadata:
  name: borrowing-service
  labels:
    app: borrowing-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: borrowing-service